[package]
name = "pafn"
version = "0.0.0"
edition = "2021"
authors = ["Tobias Hoffmann"]
license = "MIT"
description = "So far nothing, might turn into a ML library"
repository = "https://github.com/Garbaz/pafn"
[dependencies]
